apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Release.Name }}-hpa"
  namespace: "{{ .Release.Namespace }}"
spec:
  {{- with .Values.hpa }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
  - containerResource:
      container: {{ .container }}
      name: {{ .metric }}
      target:
        averageUtilization: {{ .targetUtiliation }}
        type: Utilization
    type: ContainerResource
  minReplicas: {{ .minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ $.Release.Name }}-deployment"
  {{- end }}