apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
  labels:
    app: "{{ .Release.Name }}-app"
spec:
  replicas: {{ .Values.apiserver.replicas }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-app"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-app"
    spec:
      imagePullSecrets:
        - name: pullsecret
      {{- with .Values.apiserver.containers }}
      containers:
        {{- range .}}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          resources:
            requests:
              cpu: {{ .resources.requests.cpu }}
              memory: {{ .resources.requests.memory }}
            limits:
              cpu: {{ .resources.limits.cpu }}
              memory: {{ .resources.limits.memory }}
          ports:
            {{- range .ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
            {{- end }}
          {{- if hasKey . "volumeMounts" }}
          volumeMounts:
            {{- range .volumeMounts}}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.apiserver.volumes}}
      volumes:
        {{- range . }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap.name }}
        {{- end }}
      {{- end }}