apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
  labels:
    app: "{{ .Release.Name }}-app"
spec:
  replicas: {{ .Values.apiserver.replicas }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-app"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-app"
    spec:
      imagePullSecrets:
        - name: pullsecret
      {{- with .Values.apiserver.container }}
      containers:
      - name: nginx-server
        image: nginx
        imagePullPolicy: Always
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 100Mi
            cpu: 100m
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: etc/nginx/conf.d
      - image: "{{ .image.name }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.imagePullPolicy }}
        name: {{ .name }}
        resources:
        {{- with .resources }}
          requests:
            cpu: {{ .requests.cpu }}
            memory: {{ .requests.memory }}
          limits:
            cpu: {{ .limits.cpu }}
            memory: {{ .limits.memory }}
        {{- end }}
        ports:
        - name: hello-world
          containerPort: 5000
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      {{- end }}