kind: ConfigMap
apiVersion: v1
metadata:
  name: uwsgi-configmap
data:
  uwsgi.ini: |
    plugins = python3

    # Set the module where your Django application resides
    module = sre_challenge.wsgi:application

    # Set the socket to communicate with your web server (e.g., Nginx)
    socket = /var/run/uwsgi/app/socket

    # Set the number of worker processes
    processes = 2
