- name: Copy Application Source Code, Scripts and Configs
  become: true
  ansible.builtin.unarchive:
    src: /Users/karutikimathi/playground/assessments/engie-acccess-sre-assessment/sre-assessment.tar.gz
    dest: /home/ubuntu
  tags:
    - uncompress
- name: Recursively change ownership to avoid permission errors
  file:
    path: /home/ubuntu/sre-challenge
    recurse: yes
    owner: ubuntu
    group: root
- name: Make Scripts Executable
  command: chmod -c -R ug=rwx /home/ubuntu/sre-challenge/scripts
- name: Run Application Before Install Script
  become: true
  shell: sh /home/ubuntu/sre-challenge/scripts/before_install.sh
  tags:
    - before-install
- name: Run Application After Install Script
  shell: sh /home/ubuntu/sre-challenge/scripts/after_install.sh
- name: Run Application Start Script
  shell: sh /home/ubuntu/sre-challenge/scripts/application_start.sh
- name: Run Application Stop Script
  shell: sh /home/ubuntu/sre-challenge/scripts/application_stop.sh
  tags:
    - stop_app