apiserver:
  replicas: 1
  containers:
  - name: nginx-server
    image: nginx
    imagePullPolicy: Always
    livenessProbe:
      path: "/"
      port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      path: "/"
      port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 100Mi
        cpu: 100m
    ports:
      - name: http
        containerPort: 80
    volumeMounts:
      - name: nginx-config
        mountPath: etc/nginx/conf.d
  - image: "melvinkimathi/engie-access-africa-sre-assessment:slim"
    imagePullPolicy: Always
    name: hello-world
    livenessProbe:
      path: "/"
      port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      path: "/"
      port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
    ports:
    - name: hello-world
      containerPort: 5000
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config

service:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80

hpa:
  minReplicas: 2
  maxReplicas: 10
  container: hello-world
  metric: cpu
  targetUtiliation: 60