apiserver:
  replicas: 1
  containers:
  - name: nginx-server
    image: nginx
    imagePullPolicy: Always
    livenessProbe: # check if pod is healthy
      enabled: true
      path: /
      port: 80
      initialDelaySeconds: 0
      periodSeconds: 30
      failureThreshold: 3
      successThreshold: 1
    readinessProbe: # check if pod is ready to start to accepting traffic
      enabled: true
      path: /
      port: 80
      initialDelaySeconds: 0
      periodSeconds: 30
      failureThreshold: 3
      successThreshold: 1
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 100Mi
        cpu: 100m
    ports:
      - name: http
        containerPort: 80
    volumeMounts:
      - name: nginx-config
        mountPath: etc/nginx/conf.d
  - image: "melvinkimathi/engie-access-africa-sre-assessment:1.0.0"
    imagePullPolicy: Always
    name: hello-world
    livenessProbe:
      enabled: true
      path: /
      port: 5000
      initialDelaySeconds: 0
      periodSeconds: 30
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      path: /
      port: 5000
      initialDelaySeconds: 0
      periodSeconds: 30
      failureThreshold: 3
      successThreshold: 1
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
    ports:
    - name: hello-world
      containerPort: 5000
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config

service:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80

hpa:
  minReplicas: 1 # min-replicas running at all times
  maxReplicas: 10
  container: hello-world
  metric: cpu
  targetUtiliation: 60