groups:
- name: pods
  rules:
    - alert: KubernetesPodNotHealthy
      expr: sum by (namespace, pod, country, environment, phase) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: Kubernetes Pod not healthy
        description: |
          Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a {{ $labels.phase }} state for longer than 15 minutes.
          
          VALUE = {{ $labels.phase }}

          COUNTRY: {{ $labels.country }}
          ENVIRONMENT: {{ $labels.environment }}
          NAMESPACE: {{ $labels.namespace }}

    - alert: KubernetesPodCrashLooping
      expr: increase(kube_pod_container_status_restarts_total[1m]) > 3
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Kubernetes pod crash looping
        description: |
          Pod {{ $labels.namespace }}/{{ $labels.pod }} {{  $labels.container }} is crash looping

          VALUE = {{ $value }}

          COUNTRY: {{ $labels.country }}
          ENVIRONMENT: {{ $labels.environment }}
          NAMESPACE: {{ $labels.namespace }}

    - alert: KubernetesContainerOomKiller
      expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Kubernetes Container oom killer (instance {{ $labels.pod }})
        description: |
          Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.

          VALUE = {{ $value }}

          COUNTRY: {{ $labels.country }}
          ENVIRONMENT: {{ $labels.environment }}
          NAMESPACE: {{ $labels.namespace }}